clickhouse_dbt:     # must match "profile" in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: Forbes_2000
      host: clickhouse
      port: 8123
      user: default
      password: ""
      secure: false
