# dbt_project.yml

name: 'forbes_2000'
version: '1.0'
config-version: 2

profile: 'clickhouse_profile'  # This should match your profile name in profiles.yml

# Folder configurations
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Model configurations
models:
  staging:
    +schema: "silver"        # staging tables
    +materialized: table      # default materialization for staging
  marts:
    +schema: "gold"   # gold layer tables
    +materialized: table      # default materialization for gold
  snapshots:
    +schema: "snapshots"      # snapshots for SCD2
    +materialized: snapshot

